### ISSUE TITLE
Zip error

### ISSUE THREAD

**Issue by davoooooo** [survfate/poesimpleguild#1]
When trying to Extract/Unzip, keep receiving an "unknown method" error.
Seems to be in the way the files are originally zipped.

What program are you using? I've tried WinRar as well as Google Drive Zip Extractor to no avail.

Please help!

**Comment by survfate** [comment]
I used 7zip to create the .zip file and tested with WinRAR 5.31, could you try again with 7zip?

**Comment by davoooooo** [comment]
AHHH, that makes sense.
Didn't realize I've been using WinRAR 4.0 for so long. lol
Used 5.4 and everything extracted just fine.

Thanks!
